version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: product_manager
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - '8001:8001'
            - '5173:5173'
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: product_manager
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'

volumes:
    mysql_data:
